apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pvc.yaml
- serviceaccount.yaml
- service.yaml
- networkpolicy.yaml
- deployment.yaml
- hpa.yaml
- pdb.yaml
- rolebinding.yaml

labels:
- includeSelectors: false
  pairs:
    app.kubernetes.io/managed-by: llama-stack-operator
    app.kubernetes.io/part-of: llama-stack
